name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        working-directory: src
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build -c Release --no-restore
      working-directory: src
    - name: Push NuGet package
      run: dotnet nuget push -s nuget.org -k ${{ secrets.NUGET_API_KEY }}
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
